# docker-compose.yml
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8008:8008'
#
#
#  client:
#    build:
#      context: .
#      dockerfile: ../frontend/fillActive/Dockerfile
#    ports:
#      - '4200:4200'


